name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Ensure Prismatic is not mentioned in white-label docs
        run: ./scripts/check-prismatic-references.sh
      - name: Install dependencies
        run: npm ci
      - name: Check spelling
        run: npm run check-spelling
      - name: Check markdown formatting
        run: npm run check-markdown
      - name: Copy example site config
        run: cp -R site-config.example site-config
      - name: Build docs
        run: npm run build
