name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check spelling
        run: npm run check-spelling
      - name: Check markdown formatting
        run: npm run check-markdown
      - name: Copy example site config
        run: cp -R site-config.example site-config
      - name: Build docs
        run: npm run build
